# Generated by Django 5.0.3 on 2024-04-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
